// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALV4rn3sgQp5l9JIcj6TP0Nmls9I0nLLk',
    appId: '1:345257484842:web:871a03ea3a7833d8295953',
    messagingSenderId: '345257484842',
    projectId: 'projetflutter-61e04',
    storageBucket: 'projetflutter-61e04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALV4rn3sgQp5l9JIcj6TP0Nmls9I0nLLk',
    appId: '1:345257484842:android:abcd1234efgh5678',
    messagingSenderId: '345257484842',
    projectId: 'projetflutter-61e04',
    storageBucket: 'projetflutter-61e04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALV4rn3sgQp5l9JIcj6TP0Nmls9I0nLLk',
    appId: '1:345257484842:ios:ijkl7890mnop1234',
    messagingSenderId: '345257484842',
    projectId: 'projetflutter-61e04',
    storageBucket: 'projetflutter-61e04.appspot.com',
  );
}

